### ISSUE TITLE
按照文档接入遇到问题

### ISSUE THREAD

**Issue by diguagege** [chidehang/OkOne#14]
Failed to apply plugin [id 'plugin.cdh.okone']
是否是这个plugin出问题了？

**Comment by chidehang** [comment]
有详细的构建失败信息吗，试试运行demo会不会遇到这个问题。

**Comment by diguagege** [comment]
> 有详细的构建失败信息吗，试试运行demo会不会遇到这个问题。

> Failed to apply plugin [id 'plugin.cdh.okone']
   > Extension of type 'AppExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, DefaultArtifactPublicationSet, ReportingExtension, SourceSetContainer, JavaPluginExtension, JavaInstallationRegistry, NamedDomainObjectContainer<BaseVariantOutput>, LibraryExtension, KotlinAndroidProjectExtension, KotlinTestsRegistry, AndroidExtensionsExtension, OsDetector]

这个是全部的了

**Comment by chidehang** [comment]
是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）

**Comment by diguagege** [comment]
> 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）

没问题了兄弟，谢谢您～

**Comment by diguagege** [comment]
> 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）

对了哥们，我想问问，咱们的OKOne能否配合Retrofit使用呢？

**Comment by diguagege** [comment]
04-20 17:03:32.573 16432 16941 E okone   : 1[16432][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-oBCoGc4hDkJzJ5K25nIU0g==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)

**Comment by diguagege** [comment]
> 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）

04-20 17:43:31.340 21969 23001 E okone   : 1[21969][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-paYNZ1zEH-7oYEYi1ju8mQ==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)

😂，你好，知道这个是什么原因导致的么？

**Comment by chidehang** [comment]
> > 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）
> 
> 04-20 17:43:31.340 21969 23001 E okone : 1[21969][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-paYNZ1zEH-7oYEYi1ju8mQ==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)
> 
> 😂，你好，知道这个是什么原因导致的么？

注入成员变量失败，编译的时候看看Build Output中是否有输出这样的日志：
> [OkOne] 匹配Injector: okhttp3/Request.class => plugin.cdh.okone.inject.RequestInjector@2459fca  
> [OkOne] okhttp3/Request.class->注入完成[length=7412]  
> [OkOne] okhttp3/Request.class->写入成功

**Comment by diguagege** [comment]
> > > 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）
> > 
> > 
> > 04-20 17:43:31.340 21969 23001 E okone : 1[21969][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-paYNZ1zEH-7oYEYi1ju8mQ==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)
> > 😂，你好，知道这个是什么原因导致的么？
> 
> 注入成员变量失败，编译的时候看看Build Output中是否有输出这样的日志：
> 
> > [OkOne] 匹配Injector: okhttp3/Request.class => plugin.cdh.okone.inject.RequestInjector@2459fca
> > [OkOne] okhttp3/Request.class->注入完成[length=7412]
> > [OkOne] okhttp3/Request.class->写入成功

> Task :app:transformClassesWithOkOneTransformForOfficialDebug
[OkOne] >>> transform OkOneTransform <<<
[OkOne] support incremental = false


唯一相关的就这个了

**Comment by chidehang** [comment]
> > > > 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）
> > > 
> > > 
> > > 04-20 17:43:31.340 21969 23001 E okone : 1[21969][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-paYNZ1zEH-7oYEYi1ju8mQ==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)
> > > 😂，你好，知道这个是什么原因导致的么？
> > 
> > 
> > 注入成员变量失败，编译的时候看看Build Output中是否有输出这样的日志：
> > > [OkOne] 匹配Injector: okhttp3/Request.class => plugin.cdh.okone.inject.RequestInjector@2459fca
> > > [OkOne] okhttp3/Request.class->注入完成[length=7412]
> > > [OkOne] okhttp3/Request.class->写入成功
> 
> > Task :app:transformClassesWithOkOneTransformForOfficialDebug
> > [OkOne] >>> transform OkOneTransform <<<
> > [OkOne] support incremental = false
> 
> 唯一相关的就这个了

没有扫描到okhttp的包，你是通过什么方式依赖com.squareup.okhttp3:okhttp的，还有依赖的okhttp的版本号是多少呢

**Comment by diguagege** [comment]
> > > > > 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）
> > > > 
> > > > 
> > > > 04-20 17:43:31.340 21969 23001 E okone : 1[21969][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-paYNZ1zEH-7oYEYi1ju8mQ==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)
> > > > 😂，你好，知道这个是什么原因导致的么？
> > > 
> > > 
> > > 注入成员变量失败，编译的时候看看Build Output中是否有输出这样的日志：
> > > > [OkOne] 匹配Injector: okhttp3/Request.class => plugin.cdh.okone.inject.RequestInjector@2459fca
> > > > [OkOne] okhttp3/Request.class->注入完成[length=7412]
> > > > [OkOne] okhttp3/Request.class->写入成功
> > 
> > 
> > > Task :app:transformClassesWithOkOneTransformForOfficialDebug
> > > [OkOne] >>> transform OkOneTransform <<<
> > > [OkOne] support incremental = false
> > 
> > 
> > 唯一相关的就这个了
> 
> 没有扫描到okhttp的包，你是通过什么方式依赖com.squareup.okhttp3:okhttp的，还有依赖的okhttp的版本号是多少呢

在gradle中使用下面的方式获取
api 'com.squareup.okhttp3:okhttp:4.9.0'

**Comment by chidehang** [comment]
> > > > > > 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）
> > > > > 
> > > > > 
> > > > > 04-20 17:43:31.340 21969 23001 E okone : 1[21969][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-paYNZ1zEH-7oYEYi1ju8mQ==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)
> > > > > 😂，你好，知道这个是什么原因导致的么？
> > > > 
> > > > 
> > > > 注入成员变量失败，编译的时候看看Build Output中是否有输出这样的日志：
> > > > > [OkOne] 匹配Injector: okhttp3/Request.class => plugin.cdh.okone.inject.RequestInjector@2459fca
> > > > > [OkOne] okhttp3/Request.class->注入完成[length=7412]
> > > > > [OkOne] okhttp3/Request.class->写入成功
> > > 
> > > 
> > > > Task :app:transformClassesWithOkOneTransformForOfficialDebug
> > > > [OkOne] >>> transform OkOneTransform <<<
> > > > [OkOne] support incremental = false
> > > 
> > > 
> > > 唯一相关的就这个了
> > 
> > 
> > 没有扫描到okhttp的包，你是通过什么方式依赖com.squareup.okhttp3:okhttp的，还有依赖的okhttp的版本号是多少呢
> 
> 在gradle中使用下面的方式获取
> api 'com.squareup.okhttp3:okhttp:4.9.0'

方便把完整的编译构建日志发我看下吗？现在看失败原因是因为没有扫到okhttp包导致注入失败，可能是编译过程中出现异常或者和其他gradle plugin产生冲突导致。

**Comment by diguagege** [comment]
> > > > > > > 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）
> > > > > > 
> > > > > > 
> > > > > > 04-20 17:43:31.340 21969 23001 E okone : 1[21969][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-paYNZ1zEH-7oYEYi1ju8mQ==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)
> > > > > > 😂，你好，知道这个是什么原因导致的么？
> > > > > 
> > > > > 
> > > > > 注入成员变量失败，编译的时候看看Build Output中是否有输出这样的日志：
> > > > > > [OkOne] 匹配Injector: okhttp3/Request.class => plugin.cdh.okone.inject.RequestInjector@2459fca
> > > > > > [OkOne] okhttp3/Request.class->注入完成[length=7412]
> > > > > > [OkOne] okhttp3/Request.class->写入成功
> > > > 
> > > > 
> > > > > Task :app:transformClassesWithOkOneTransformForOfficialDebug
> > > > > [OkOne] >>> transform OkOneTransform <<<
> > > > > [OkOne] support incremental = false
> > > > 
> > > > 
> > > > 唯一相关的就这个了
> > > 
> > > 
> > > 没有扫描到okhttp的包，你是通过什么方式依赖com.squareup.okhttp3:okhttp的，还有依赖的okhttp的版本号是多少呢
> > 
> > 
> > 在gradle中使用下面的方式获取
> > api 'com.squareup.okhttp3:okhttp:4.9.0'
> 
> 方便把完整的编译构建日志发我看下吗？现在看失败原因是因为没有扫到okhttp包导致注入失败，可能是编译过程中出现异常或者和其他gradle plugin产生冲突导致。

好，我输出一下，另外，方便给个联系方式么？qq或者wechat。沟通会稍微方便点，如果不方便，我们就这儿说。😂，不管怎么样都谢谢您

**Comment by chidehang** [comment]
> > > > > > > > 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）
> > > > > > > 
> > > > > > > 
> > > > > > > 04-20 17:43:31.340 21969 23001 E okone : 1[21969][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-paYNZ1zEH-7oYEYi1ju8mQ==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)
> > > > > > > 😂，你好，知道这个是什么原因导致的么？
> > > > > > 
> > > > > > 
> > > > > > 注入成员变量失败，编译的时候看看Build Output中是否有输出这样的日志：
> > > > > > > [OkOne] 匹配Injector: okhttp3/Request.class => plugin.cdh.okone.inject.RequestInjector@2459fca
> > > > > > > [OkOne] okhttp3/Request.class->注入完成[length=7412]
> > > > > > > [OkOne] okhttp3/Request.class->写入成功
> > > > > 
> > > > > 
> > > > > > Task :app:transformClassesWithOkOneTransformForOfficialDebug
> > > > > > [OkOne] >>> transform OkOneTransform <<<
> > > > > > [OkOne] support incremental = false
> > > > > 
> > > > > 
> > > > > 唯一相关的就这个了
> > > > 
> > > > 
> > > > 没有扫描到okhttp的包，你是通过什么方式依赖com.squareup.okhttp3:okhttp的，还有依赖的okhttp的版本号是多少呢
> > > 
> > > 
> > > 在gradle中使用下面的方式获取
> > > api 'com.squareup.okhttp3:okhttp:4.9.0'
> > 
> > 
> > 方便把完整的编译构建日志发我看下吗？现在看失败原因是因为没有扫到okhttp包导致注入失败，可能是编译过程中出现异常或者和其他gradle plugin产生冲突导致。
> 
> 好，我输出一下，另外，方便给个联系方式么？qq或者wechat。沟通会稍微方便点，如果不方便，我们就这儿说。😂，不管怎么样都谢谢您

我也很好奇遇到的问题，QQ：554573290，欢迎交流啊

**Comment by diguagege** [comment]
> > > > > > > > > 是在lib module中apply plugin还是在app module中apply plugin。（先试试clone这个工程运行demo，然后搬demo中的配置）
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 04-20 17:43:31.340 21969 23001 E okone : 1[21969][Thread[OkHttp https://activity.funnymamu.com/...,5,main]][okone]No field okone_priority of type I in class Lokhttp3/Request; or its superclasses (declaration of 'okhttp3.Request' appears in /data/app/com.nebula.mamu-paYNZ1zEH-7oYEYi1ju8mQ==/base.apk!classes5.dex)(RequestPriorityProcessor.kt:37)
> > > > > > > > 😂，你好，知道这个是什么原因导致的么？
> > > > > > > 
> > > > > > > 
> > > > > > > 注入成员变量失败，编译的时候看看Build Output中是否有输出这样的日志：
> > > > > > > > [OkOne] 匹配Injector: okhttp3/Request.class => plugin.cdh.okone.inject.RequestInjector@2459fca
> > > > > > > > [OkOne] okhttp3/Request.class->注入完成[length=7412]
> > > > > > > > [OkOne] okhttp3/Request.class->写入成功
> > > > > > 
> > > > > > 
> > > > > > > Task :app:transformClassesWithOkOneTransformForOfficialDebug
> > > > > > > [OkOne] >>> transform OkOneTransform <<<
> > > > > > > [OkOne] support incremental = false
> > > > > > 
> > > > > > 
> > > > > > 唯一相关的就这个了
> > > > > 
> > > > > 
> > > > > 没有扫描到okhttp的包，你是通过什么方式依赖com.squareup.okhttp3:okhttp的，还有依赖的okhttp的版本号是多少呢
> > > > 
> > > > 
> > > > 在gradle中使用下面的方式获取
> > > > api 'com.squareup.okhttp3:okhttp:4.9.0'
> > > 
> > > 
> > > 方便把完整的编译构建日志发我看下吗？现在看失败原因是因为没有扫到okhttp包导致注入失败，可能是编译过程中出现异常或者和其他gradle plugin产生冲突导致。
> > 
> > 
> > 好，我输出一下，另外，方便给个联系方式么？qq或者wechat。沟通会稍微方便点，如果不方便，我们就这儿说。😂，不管怎么样都谢谢您
> 
> 我也很好奇遇到的问题，QQ：554573290，欢迎交流啊

好，加你了。上扣扣聊
