### ISSUE TITLE
关于OkHttpBuilder属性对比的问题

### ISSUE THREAD

**Issue by o03150** [chidehang/OkOne#16]
/**
     * 创建配方一
     */
    private fun createBuilder1(): OkHttpClient.Builder {
        return OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
            .eventListener(mEventListener)
    }

    /**
     * 创建配方二
     */
    private fun createBuilder2(): OkHttpClient.Builder {
        val httpLoggingInterceptor = HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.HEADERS)
        return OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .addInterceptor(httpLoggingInterceptor)
            .eventListener(mEventListener)
方法1创建了一个OkHttpClient,并且缓存了下来
但是方法2我把拦截器HttpLoggingInterceptor的属性更改了,在属性对比时并没有返回false,而是直接忽略了
导致无论方法2如何调用,始终用的是方法1的okHttpClient,而方法2的拦截器则无法生效！

**Comment by chidehang** [comment]
确实有这个问题，内部比较配置项的时候，只对比HttpLoggingInterceptor自身，没有再对比HttpLoggingInterceptor中的属性。只能再追加设置一个不相关的配置，或者自定义一个HttpLoggingInterceptor来规避这个问题。

**Comment by chidehang** [comment]
确实有这个问题，内部比较配置项的时候，只对比HttpLoggingInterceptor自身，没有再对比HttpLoggingInterceptor中的属性。只能再追加设置一个不相关的配置，或者自定义一个HttpLoggingInterceptor来规避这个问题。
